name: Pylint

on:
  push:
    branches: [ "main" ]
  pull_request_target:
    branches: [ "main" ]

jobs:
  Run Pylint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint utils
        pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
